---

- hosts: all
  user: robby
  sudo: True

  tasks:

    - name: update apt
      action: command apt-get update

    - name: install pip
      action: apt pkg=python-pip state=latest

    - name: install base apt packages
      action: apt pkg=$item state=latest
      with_items:
        - gcc
        - screen
        - htop
        - bmon
        - git
        - make
        - python-virtualenv
        - python-dev
        - python-software-properties
        - squid
        - sysstat

    - name: download redis 2.6
      action: command wget -O /tmp/redis-2.6.tar.gz http://redis.googlecode.com/files/redis-2.6.0-rc7.tar.gz

    - name: decompress redis 2.6
      action: shell cd /tmp; tar xvfz redis-2.6.tar.gz

    - name: make redis 2.6
      action: command make /tmp/redis-2.6.0-rc7

    - name: install redis 2.6
      action: shell cd /tmp/redis-2.6.0-rc7; make; sudo make install;

    - name: install redis upstart script
      action: shell echo "start on runlevel [23]\nstop on shutdown\nexec /usr/local/bin/redis-server\nrespawn" > /etc/init/redis-server.conf

    - name: start redis
      action: command start redis-server
      ignore_errors: True

    - name: create service directory
      action: file dest=/var/services/ state=directory

    - name: create virtual env
      action: command /usr/bin/virtualenv /var/services/image_scraper/env
      ignore_errors: True

    - name: create output directory
      action: file dest=/var/services/image_scraper/output state=directory

    - name: create app directory
      action: file dest=/var/services/image_scraper/app state=directory

    - name: create log
      action: command touch /var/log/image-scraper.log

    - name: chown log
      action: command chown www-data. /var/log/image-scraper.log

    - name: chmod log
      action: command chmod ug+rw /var/log/image-scraper.log

    - name: create service upstart script
      action: shell echo "start on runlevel [23]\nstop on shutdown\nexec /var/services/image_scraper/env/bin/python /var/services/image_scraper/app/scrape_flow.py >> /var/log/image-scraper.log 2>&1\nrespawn" > /etc/init/image-scraper.conf

    - name: add cron to re-scrape
      action: shell echo "0 * * * *  /var/services/image_scraper/env/bin/python /var/services/image_scraper/app/add_sites.py 20 >> /var/log/image_scraper.log" > /etc/cron.d/image_scraper_add_sites

    #- name: start service
    #  action: command start image-scraper
